### ISSUE TITLE
使用MySQL报错Column 'id' cannot be null。

### ISSUE THREAD

**Issue by Neptune1990** [manipEgo/koishi-plugin-bangumi-onair#1]
使用数据库为MySQL
报错：
![image](https://github.com/manipEgo/koishi-plugin-bangumi-onair/assets/107494041/61a837e6-c1b9-45a4-aab0-f608ea7333ac)
创建表时id无自动递增且要求不是null
![image](https://github.com/manipEgo/koishi-plugin-bangumi-onair/assets/107494041/652e077a-bb3a-4c72-913c-202ed27c1287)
![image](https://github.com/manipEgo/koishi-plugin-bangumi-onair/assets/107494041/98ef0b56-e655-4036-bc4a-a32d0fc2e15b)
但新增id数据都是null。
![image](https://github.com/manipEgo/koishi-plugin-bangumi-onair/assets/107494041/e14c09e8-ac0f-4da3-8346-27c129f10482)

System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700

Binaries:
    Node: 20.3.1
    Yarn: 4.0.1

Koishi:
    Core: 4.16.3
    Console: 5.22.6
    Koishi Desktop: 1.0.0

**Comment by manipEgo** [comment]
已解决，稍后发布修复版本，谢谢反馈
