### ISSUE TITLE
使用update命令显示“CDN 数据获取失败”

### ISSUE THREAD

**Issue by johntime2005** [manipEgo/koishi-plugin-bangumi-onair#2]
`TypeError: Cannot read properties of undefined (reading 'items')
                            at /koishi/node_modules/koishi-plugin-bangumi-onair/lib/index.js:169:29
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
`
![image](https://github.com/user-attachments/assets/d26cf30e-ae8a-4341-9c53-d2868c228d55)

**Comment by manipEgo** [comment]
感谢反馈。

错误未能成功复现，但问题应该在于没能顺利从 CDN 下载数据。数据链接是[这个](https://cdn.jsdelivr.net/npm/bangumi-data/dist/data.json)。请确认一下你的 Koishi 部署环境能够顺利访问这个网址。我考虑近期增加自定义 CDN 链接的功能，方便替换为镜像站。

**Comment by manipEgo** [comment]
[release v1.6.0](https://github.com/manipEgo/koishi-plugin-bangumi-onair/releases/tag/v1.6.0) 已新增自定义 CDN 的功能，如果不是无法访问 CDN 导致的问题欢迎提供更多信息新开 issue 提出~

closed by [release v1.6.0](https://github.com/manipEgo/koishi-plugin-bangumi-onair/releases/tag/v1.6.0)
